title: logs
description: GitHub Pages + Jekyll で運用するブログ
url: "https://yozniax.github.io"
baseurl: "/logs"

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: Your Name

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - Dockerfile
  - docker-compose.yml
  - vendor
